version: '2'
services:
services:
  prplserver:
    build:
      context: .
      dockerfile: docker/Dockerfile.prplserver
    ports:
      - "8080:8080"
  customelement:
    build:
      context: .
      dockerfile: docker/Dockerfile.customelement
    ports:
      - "8080:8080"
  contracts:
    build:
      context: .
      dockerfile: docker/Dockerfile.contracts
  lint:
    build:
      context: .
      dockerfile: docker/Dockerfile.lint
